import {styleNames} from './provider-theme.js';
// Cerebras does not constrain string patterns/lengths or array lengths. Numeric
// RGB and eight nullable named layers make these bounds enforceable in decoding.
// Shared definitions keep the provider prompt compact without changing its constraints.
const channel={type:'integer',minimum:0,maximum:255};
const color={type:'object',additionalProperties:false,properties:{r:channel,g:channel,b:channel},required:['r','g','b'],description:'sRGB channels 0-255. Warm ivory: r=250,g=248,b=240. Choose subtle material colors; never pack into one integer.'};
const rgb={$ref:'#/$defs/color'};
const shape={type:'object',additionalProperties:false,properties:{kind:{type:'string',enum:['ellipse','rect','line']},x:{type:'number',minimum:0,maximum:1000},y:{type:'number',minimum:0,maximum:1000},width:{type:'number',minimum:0,maximum:1000},height:{type:'number',minimum:0,maximum:1000},rotation:{type:'number',minimum:0,maximum:360},fill:rgb,stroke:rgb,opacity:{type:'number',minimum:0,maximum:0.3}},required:['kind','x','y','width','height','rotation','fill','stroke','opacity']};
const slots=Array.from({length:8},(_,i)=>'layer'+i);
export const themeSchema={$defs:{color,shape,pattern:{type:'object',additionalProperties:false,properties:{kind:{type:'string',enum:['none','ruled','grid','dots']},color:rgb,spacing:{type:'integer',minimum:16,maximum:64},opacity:{type:'number',minimum:0,maximum:0.25}},required:['kind','color','spacing','opacity']}},type:'object',additionalProperties:false,properties:{visual:{type:'object',additionalProperties:false,properties:Object.fromEntries(['canvasCss','cardCss','headingCss','titleCss','sceneSvg','cardSvg'].map(k=>[k,{type:'string'}])),required:['canvasCss','cardCss','headingCss','titleCss','sceneSvg','cardSvg']},name:{type:'string',enum:styleNames},background:rgb,surface:rgb,text:rgb,muted:rgb,accent:rgb,urgentColor:rgb,art:{type:'object',additionalProperties:false,properties:{angle:{type:'integer',minimum:0,maximum:360},start:rgb,end:rgb,pattern:{$ref:'#/$defs/pattern'},shapes:{type:'object',additionalProperties:false,properties:Object.fromEntries(slots.map(k=>[k,{anyOf:[{$ref:'#/$defs/shape'},{type:'null'}]}])),required:slots}},required:['angle','start','end','pattern','shapes']},radius:{type:'integer',minimum:0,maximum:24},font:{type:'string',enum:['sans','serif']},density:{type:'string',enum:['compact','comfortable']},layout:{type:'string',enum:['columns','stacked']}},required:['visual','name','background','surface','text','muted','accent','urgentColor','art','radius','font','density','layout']};

